### ISSUE TITLE
Don't import.

### ISSUE THREAD

**Issue by mikefromru** [libeclipse/visionary#1]
I have Python3.4 and when i wite "import visionarypm" I get the error.

  File "/home/google/.virtualenvs/env3.4/lib/python3.4/site-packages/visionarypm/**init**.py", line 38
    print err('Input unusable.\n')
            ^
SyntaxError: invalid syntax

**Comment by awnumar** [comment]
Visionary only supports python2 for now.

**Comment by awnumar** [comment]
There. Visionary now supports both versions of python.
