### ISSUE TITLE
vpm command not recognized, ubuntu 16.10

### ISSUE THREAD

**Issue by musicformellons** [libeclipse/visionary#10]
I get:
usr@usr:~$ pip install visionarypm
Collecting visionarypm
Collecting colorama (from visionarypm)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting pyscrypt (from visionarypm)
Installing collected packages: colorama, pyscrypt, visionarypm
Successfully installed colorama-0.3.7 pyscrypt-1.6.2 visionarypm-2.0.4
usr@usr:~$ vpm
No command 'vpm' found, but there are 34 similar ones
vpm: command not found

**Comment by awnumar** [comment]
Try the `python` command. Does that work?

**Comment by musicformellons** [comment]
gives:
usr@usr:~$ python
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by awnumar** [comment]
Try these commands:

`ls /usr/bin | grep vpm`
`cat /usr/bin/vpm`

**Comment by musicformellons** [comment]
Looks like ubuntu 16 puts it in a non-typical folder (i.e. /home/usr/.local/bin/ ):

usr@usr:~$ ls /usr/bin | grep vpm
usr@usr:~$ cat /usr/bin/vpm
cat: /usr/bin/vpm: No such file or directory

usr@usr:~/.local/bin$ ls
bashmarks.sh  virtualenv        virtualenvwrapper_lazy.sh  vpm
pbr           virtualenv-clone  virtualenvwrapper.sh
usr@usr:~/.local/bin$

**Comment by awnumar** [comment]
is that folder in your path?

Also do:
`cat ~/.local/bin/vpm`

**Comment by tobbbles** [comment]
Add local bin to your path.

`export PATH=$PATH:~/.local/bin`

**Comment by musicformellons** [comment]
Works now, thanks!
