### ISSUE TITLE
Better memory security

### ISSUE THREAD

**Issue by waynew** [libeclipse/visionary#11]
Right now there are two easy(?) attack vectors:
- PW shows up in the terminal scrollback
- if you copy to clipboard, the PW stays in clipboard.

For the latter it's a pretty easy fix, clear the clipboard after N seconds or when vpm exits.

The former is a bit trickier. I don't know about tmux/screen, but a curses style approach would be one way to clear it from the screen. As an alternative, maybe just let the pw be copied direct to the clipboard. On Linux-style terminals you can use escape sequences to [move the cursor around](http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html). I'm fairly certain that there are _some_ things that can be done on Windows, but I'm not really aware of anything sane. Probably the most naive approach would be to just do something like:

```
 print('password', end='\r')
 time.sleep(5)
 print('XXXXXXXX No password here!')
```

**Comment by awnumar** [comment]
Terminal scrollback isn't a problem really, unless your stdout is logged somewhere. Usually it's cleared as soon as you exit your terminal emulator.

With the clipboard, sometimes on unix systems is xclip is not installed it will fail to copy the password to clipboard. Also, it will override whatever is in the clipboard without asking the user.

**Comment by tobbbles** [comment]
Personally, I'd rather not have a 3rd party script touch my clipboard. If this was to be implemented there would need to be a prompt for user's consent.

**Comment by awnumar** [comment]
Currently there's a prompt but it's alongside stdout.

**Comment by awnumar** [comment]
> print('password', end='\r')
> time.sleep(5)
> print('XXXXXXXX No password here!')

This would prevent people from entering other keywords while the timer runs out. And 5 seconds is small. I can't think of another solution than just `clear` and advise to exit the terminal.
