### ISSUE TITLE
Non-sudo dependency install

### ISSUE THREAD

**Issue by tobbbles** [libeclipse/visionary#16]
Currently you can't specify to install dependencies in the user directory. If a user wants to use this and doesn't have access to root, they cannot.
## Proposal

Add a `--user` flag to the setup script to install in the user's home directory

**Comment by awnumar** [comment]
This would only work if the folder that they install it to is in their path. Otherwise the vpm command wouldn't work.

**Comment by awnumar** [comment]
Pip has support for this already:

`pip install visionarypm --user username`

Then you just add the installation directory to your path.
