### ISSUE TITLE
Compare with Masterpasswordapp

### ISSUE THREAD

**Issue by andreas-becker** [libeclipse/visionary#3]
Hey,
sorry for writing an "issue", but i did not find another way to contact you.

Maybe you didn't know, but the Master Password (http://masterpasswordapp.com/) Tool seems like going into the same direction. 

Kind regards

**Comment by awnumar** [comment]
Thanks for informing me, however visionary has no affiliation, nor intends to in the future.

I can be contacted here:
hi@libeclipse.me
http://libeclipse.me
