### ISSUE TITLE
Only Two Password Formats

### ISSUE THREAD

**Issue by the-gingerbread-man** [libeclipse/visionary#35]
Many sites (iCloud for one) have complicated password requirements-- ie. passwords must contain caps and lowercase, passwords must contain >=1 number, passwords must contain >1 symbol. Extend the configurability to add more possible formats for each password, at least one with symbols and uppercase letters included.

**Comment by awnumar** [comment]
I'll need some kinda deterministic algorithm to generate these. I'm thinking maybe just get the first letter of every word in the readable password with a period at the end. Not sure about numbers.

**Comment by awnumar** [comment]
I'm open to ideas on how to solve this.

**Comment by rubik** [comment]
- From the conventional password, we may transform it by using a permutation of the characters we want to add:

``` python
import math
import string
import random

# A random shuffle of string.punctuation + string.ascii_uppercase
to_add = '*>OI+D~}E{AF"`KXR\[J:-&#BQWN;$%TGPZ.=U,_HS()@L\'|<M]YCV/?!^'
required = (string.ascii_lowercase,
            string.ascii_uppercase,
            string.digits,
            string.punctuation)


def nth_perm(S, n):
    '''Compute the n-th lexicographic permutation of the alphabet S.'''
    p = []
    for l in range(len(S) - 1, -1, -1):
        i, n = divmod(n, math.factorial(l))
        p.append(S[i])
        S = S[:i] + S[i + 1:]
    return p


def transform(keyword, password):
    res = []
    perm_number = len(keyword) * sum(map(ord, keyword))
    chosen_perm = nth_perm(to_add, perm_number % math.factorial(len(to_add)))
    for i, c in enumerate(password):
        # 2/3 of the original is preserved
        if i % 3:
            res.append(c)
            continue
        # We index from the bottom of the string, because that's where the
        # permutation changes most
        res.append(chosen_perm[-((i + len(keyword)) % len(to_add) + 1)])
    # There's a little possibility that the required chars aren't there
    for i, req in enumerate(required):
        if not set(req).intersection(res):
            res[i] = req[0]
    return ''.join(res)
```

  The string `to_add` was shuffled just to mix the characters, in order to avoid many repetitions when we do `chosen_perm[...]`. Also, we index `chosen_perm` from the bottom and we use negative indices because otherwise the results would be too similar of even identical for different keywords.
- For the readable password, we might add a symbol or an uppercase letter in between the words. The additional characters could be chosen depending on the length / characters of the preceding word. The end result would be something like:

```
Diffidence_6_hollers_*_fluorocarbon_U_varnished_-_traffic
```

**Comment by awnumar** [comment]
@rubik Thanks for the comment. I've been busy recently so haven't had time to properly check it out. Is that algorithm deterministic? I see you used the random module.

**Comment by rubik** [comment]
@libeclipse Yes, it's deterministic. Actually the random module is a leftover from a previous version and I've only used it to generate the `to_add` string. This is just to get better looking passwords.

**Comment by awnumar** [comment]
@rubik could you look over that PR?
