### ISSUE TITLE
Can't run on OS X El Capitan

### ISSUE THREAD

**Issue by ghost** [libeclipse/visionary#36]
Maybe I'm being dumb. Probably I'm being dumb. But I get the following after installing `vpm` successfully:

```
ImportError: No module named _scrypt
```

Any ideas?

**Comment by tobbbles** [comment]
It's probably a path issue, mainly with pip and where it installs dependencies

**Comment by ghost** [comment]
Thought so, but I can use every other thing I installed with `pip`.

**Comment by awnumar** [comment]
It seems something went wrong with the scrypt installation. Could you try

sudo pip install scrypt

**Comment by ghost** [comment]
Yeah, didn't fix the problem. `scrypt` is installed too. I've my `pip` set up to not require _sudo_. No worries, we can close the issue anyway :)

**Comment by awnumar** [comment]
So is scrypt definitely installed? Try opening a Python interactive session and importing Scrypt.

**Comment by awnumar** [comment]
Wait if your pip doesn't require sudo, then does that mean everything is installed locally instead of in the system directories? This might be the cause.

**Comment by ghost** [comment]
I uninstalled `scrypt`. Installed `visionarypm` afterwards, even though it was installed. `scrypt` as a dependency was fixed, and now it works! Sorry for killing some of your time, should've tried uninstalling `scrypt` before.
