### ISSUE TITLE
Safety concerns

### ISSUE THREAD

**Issue by kootenpv** [libeclipse/visionary#4]
As far as I understand, the password depends on the config file, the master password and the keyword. Given those, there will be a determined password.

The keyword would be guessable, as for "facebook" it would be either just "facebook", "facebook.com" or some slight variation. If not, then the person themselves cannot remember them.

The config file, as you said, also contains only few variations: you propose that if you lose it you can just guess them to get your password back.

So, in the end what you end up with is a system where practically all passwords end up depending only on the master password?

Just trying to understand...

**Comment by awnumar** [comment]
You're pretty much correct.

The keyword acts as a salt, which can be public, and the config can be disclosed too. Scrypt runs and  derives a key from the input.

Given a generated password and all the info that can be shared, the only way to break it would be to brute force,  and scrypt makes this infeasible.

Phishing wouldn't work if the user uses a unique master password, and keylogging would compromise everything even without the master password being discovered.

I'm planning on writing a go implementation where I can knock the scrypt cost factors up massively.

Issues are really for bugs. I can be contacted at my email here: libeclipse@gmail.com
