### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by bogdanm** [libeclipse/visionary#5]
It seems like offering 2FA support as an option would increase the overall security of the project (which is pretty awesome BTW). See for example https://github.com/pyotp/pyotp

**Comment by awnumar** [comment]
I'll look into it.

**Comment by bogdanm** [comment]
On second thought, that might not work as well as I thought, given that you need to store the secret key somewhere. Even if you'd need to type it every time the program starts, you'd end up with a system that uses two passwords instead of one, which isn't really more secure.

**Comment by awnumar** [comment]
Well it could be encrypted with the master key and then stored in the normal configuration file.

**Comment by bogdanm** [comment]
Sure, but then if the master password is compromised, you'd automatically have access to the 2FA secret too, right? Sorry if I'm missing something.

**Comment by awnumar** [comment]
Hmm I guess you're right.
