### ISSUE TITLE
Weak default parameters

### ISSUE THREAD

**Issue by javier-lopez** [libeclipse/visionary#9]
As per Colin Percival [recommendations](http://www.tarsnap.com/scrypt/scrypt-slides.pdf) (page 17) 2009 the following default values should be considered when using scrypt as KDF (which are now rather low).
- For interactive use, N = 2^14, r = 8, p = 1
- For sensitive storage, N = 2^20, r = 8, p = 1

However in visionary the defaults are, N = 2^11, r = 1, p = 1 and the maximum allowed are N = 2^14, r = 1, p = 1 both are below the minimum recommended.

The scrypt key derivation function has been implemented in several languages, thus even if takes enough time on python (and may feel safe), it could be run in faster languages/custom hardware allowing effective brute force attacks, in a [C implementation](https://github.com/technion/libscrypt)

N = 2^11, r = 1, p = 1 takes:
real    0m0.004s
user    0m0.003s
sys 0m0.001s

While N = 2^14, r = 1, p = 1 takes:
real    0m0.007s
user    0m0.006s
sys 0m0.001s

Not only default visionary parameters can be calculated quite fast, but require little ram, allowing more attacks in parallel.

128 bytes x N_cost x r_blockSizeFactor = 128 x 2048 x 1 = 262144 bytes = 256kb
128 bytes x N_cost x r_blockSizeFactor = 128 x 16384 x 1 = 2097152 bytes = 2MB

The recommended for interactive usage is 16 MB while for sensitive information is 1GB

**Comment by awnumar** [comment]
The thing is , Python is really really slow. I'm working on a Go implementation which will be much faster. When that's done, the Python one will be depreciated.

**Comment by yoavram** [comment]
If pure python is too slow, you might have nsider using a python c-wrapper - see instructions in https://github.com/ricmoo/pyscrypt/blob/master/README.md
Also, if the click library provides many of the CLI utilities you wrote yourself, see click.pocoo.org/

Otherwise: cool project!

**Comment by kootenpv** [comment]
Also worth noting (pip pylibscypt vs pyscrypt) at the low N=2**11:

```
In [31]: timeit bench_pylibscript()
1000 loops, best of 3: 838 µs per loop

In [32]: timeit bench_pyscrypt()
1 loops, best of 3: 488 ms per loop
```

And for N=2**14:

```
In [38]: timeit bench_pylibscript()
100 loops, best of 3: 6.33 ms per loop

In [39]: timeit bench_pyscrypt()
1 loops, best of 3: 3.8 s per loop
```

**Comment by awnumar** [comment]
I'm just on the verge of commiting a massive update to use a different scrypt module. Scrypt speed will be much much faster. It breaks reverse compatability though because for some reason the generated passwords are different.

**Comment by kootenpv** [comment]
Watch out with encodings. Changing the scrypt parameters will logically change the password.

**Comment by awnumar** [comment]
Yeah I tested it with the old parameters. I'll look over the encodings.

**Comment by awnumar** [comment]
It still breaks reverse compatability I believe. :/

**Comment by yoavram** [comment]
Maybe the scrypt module can be part of the configuration? That way you may be able to keep backwards compatibility. Just a guess

**Comment by awnumar** [comment]
Na that's just extra bloat. People can use

`pip install visionarypm==2.0.2`

If they want the old less secure version.

**Comment by chilicuil** [comment]
If visionary could provide options to set N, r and p on scrypt it will be backwards compatibility as users could set older settings or their own.

**Comment by awnumar** [comment]
Wow I'm stupid. I changed N but left r when testing reverse compatability.

I don't think there's a point in letting people configure r and p. It's just extra complications for the end user. Lets face it, most users aren't crypto-aware, and will be easily confused by too many configuration options.
